### ISSUE TITLE
Verify works on android

### ISSUE THREAD

**Issue by saulshanabrook** [saulshanabrook/react-native-webview-crypto#1]
update https://github.com/facebook/react-native/issues/1424 when finished

**Comment by nadinelyab** [comment]
Hi @LinusU,
I'd like to use this library and I'm wondering if there are any plans to support Android soon. 
Thanks

**Comment by LinusU** [comment]
Hey,

I recently got this merged facebook/react-native#20366 into React Native. That should be a part of the 0.57 release which should be out very soon. With that in, we should be able to switch to the built-in WebView, which should work for both iOS and Android.

There is also a problem with accessing `crypto.subtle` on the `about:blank` page on Android. A workaround is to include a `blank.html` file inside the resources folder. Need to look in a bit more into that...

**Comment by nadinelyab** [comment]
Awesome! Thanks for working on this project. I will try to work on the `about:blank` page bug as well and submit a PR if I get anywhere with it.

**Comment by LinusU** [comment]
Awesome, that would be great!

**Comment by nadinelyab** [comment]
@LinusU it doesn't look like your PR made it into 0.57.0-rc.0, but maybe if you request that it be cherry picked in [this discussion](https://github.com/react-native-community/react-native-releases/issues/34) it will be?

**Comment by sirpy** [comment]
fixed
