### ISSUE TITLE
Webview-crypto won't work with last versions of Chrome webview

### ISSUE THREAD

**Issue by voliva** [saulshanabrook/react-native-webview-crypto#10]
From https://www.chromium.org/blink/webcrypto

> Access to the WebCrypto API is restricted to secure origins (which is to say https:// pages).

When react-native-webview-crypto creates the WebViewBridge it specifies for URI `about:blank` which isn't considered secure by chrome (And so most of newest androids) - As of now, if you open `about:blank` page in chrome (72.0), open the console and run `window.crypto.subtle` you'll get undefined. If you try the same on any HTTPS site you'll get the crypto API

A possible workaround would be for WebViewBridge to open a HTTPS website... but then that means that the crypto module will need an internet connection to run.

Is there any other way for the webview to accept an offline site as secure?

**Comment by LinusU** [comment]
This is unfortunate 🤔 

If it's possible I would love to see a workaround for this that *doesn't* involve any network requests to a secure domain...

**Comment by saulshanabrook** [comment]
Hey @voliva this is indeed unfortunate. I am not sure, I am not actively using this package anymore. If you are interested in helping maintain it, I am happy to give you commit rights.

**Comment by sirpy** [comment]
@voliva you can give it https://localhost
you can now use isomorphic-webcrypto it works on react-native also. not 100% webcrypto compatible but most of it is there

**Comment by sirpy** [comment]
@voliva fixed, you need to create blank.html on android, see new readme
