### ISSUE TITLE
Use new webview API for react native

### ISSUE THREAD

**Issue by saulshanabrook** [saulshanabrook/react-native-webview-crypto#7]

**Comment by sinewave440hz** [comment]
Hi. I'm guessing this isn't currently maintained. Any plans to revive it, may I ask?

**Comment by LinusU** [comment]
@saulshanabrook I would be interested in taking over the project!

**Comment by saulshanabrook** [comment]
@LinusU Great! I have added you as a collaborator on this repo as well as the `webview-crypto` repo since that is where some of the logic lives. If you post your npm account, I will add you to both the packages there so you can publish to them. I will remove the text about it being maintained by Burke Software. There are also two projects for nativescript and nativescript angular, if you wanna do anything with those, lemme know and I can give you access to them as well. Does that sound OK?

**Comment by saulshanabrook** [comment]
Also, if you have any Qs about the codebase or want a second opinion on anything feel free to reach out and we could setup a time to have a call or discuss via issues. Otherwise, have fun!

**Comment by LinusU** [comment]
Sorry for the delay in answering, went on a long vacation just after posting this 🙈 I'm back in a few days.

Personally not using nativescript, but I'd be happy to help with merging PRs and triaging issues.

I'm `linusu` on npm 👏

**Comment by saulshanabrook** [comment]
No worries. You should now have access to:

* https://www.npmjs.com/package/webview-crypto / https://github.com/saulshanabrook/webview-crypto
* https://www.npmjs.com/package/react-native-webview-crypto / https://github.com/saulshanabrook/react-native-webview-crypto
* https://www.npmjs.com/package/nativescript-angular-webview-crypto / https://github.com/saulshanabrook/nativescript-angular-webview-crypto
* https://www.npmjs.com/package/nativescript-webview-crypto / https://github.com/saulshanabrook/nativescript-webview-crypto

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
I don't know if I'm going crazy, but it seems like `window.crypto.subtle` isn't available when you are on the `about:blank` page 🤔 

Might have to do with this: https://developers.google.com/web/updates/2017/06/chrome-60-deprecations

Not sure how to solve that in a nice way 🤔 will have to investigate more

**Comment by sirpy** [comment]
fixed
